version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:@postgres:5432/osrs-bingo?schema=public
    volumes:
      - .:/workspace
    command: sleep infinity
    networks:
      - devnet
    depends_on:
      - postgres
    env_file:
      - .env.local

  postgres:
    container_name: osrs-bingo_postgres
    image: postgres:17-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=  # Empty password is fine here
      - POSTGRES_DB=osrs-bingo
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - devnet

  dbmate:
    image: amacneil/dbmate
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:@postgres:5432/osrs-bingo?sslmode=disable
    volumes:
      - .:/app
    working_dir: /app
    command: up
    networks:
      - devnet

volumes:
  postgres:

networks:
  devnet:
    driver: bridge
