services:
  app:
    working_dir: /osrs-bingo
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ~/.ssh:/root/.ssh:ro
      - osrs-bingo-data:/osrs-bingo
      - ${ZSHRC_PATH:-/dev/null}:/root/.zshrc
      - ${NEOVIM_CONFIG_PATH:-/dev/null}:/root/.config/nvim
      - nvim-data:/root/.local/share/nvim # Persist plugins
      - nvim-state:/root/.local/state/nvim
      - nvim-cache:/root/.cache/nvim
    stdin_open: true
    tty: true
    command: zsh
    env_file:
      - .env
    networks:
      - devnet
    depends_on:
      - postgres

  postgres:
    container_name: osrs-bingo_postgres
    image: postgres:17-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD= # Empty password is fine here
      - POSTGRES_DB=osrs-bingo
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - devnet
    pgadmin:
      image: dpage/pgadmin4:latest
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL:  admin@you.com
        PGADMIN_DEFAULT_PASSWORD: secret
      ports:
        - "8080:80"      # maps http://localhost:8080 to pgAdmin UI
      volumes:
        - pgadmin-data:/var/lib/pgadmin
      depends_on:
        - db

  dbmate:
    image: amacneil/dbmate
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:@postgres:5432/osrs-bingo?sslmode=disable
    volumes:
      - .:/app
    working_dir: /app
    command: up
    networks:
      - devnet

volumes:
  postgres:
  nvim-data:
  nvim-state:
  nvim-cache:
  osrs-bingo-data:


networks:
  devnet:
    driver: bridge
